server:
  port: 9003
  shutdown: graceful
spring:
  application:
    name: modu-square-view-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3307/article_view}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:127.0.0.1:9092}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      service: ${spring.application.name}
